[package]
name = "langtons-ant"
version = "0.1.0"
authors = ["ZKtheMAN <zakhattak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2="*"
spin_sleep="*"